spring:
  security:
    oauth2.client:
      registration:
        google:
          clientId: ${OAUTH_GOOGLE_CLIENT_ID:id}
          clientSecret: ${OAUTH_GOOGLE_CLIENT_SECRET:secret}
          scope:
            - email
            - profile
  data:
    mongodb:
      host: ${MONGO_DB_HOST:localhost}
      port: ${MONGO_DB_PORT:27017}
      database: onlineJudgeDB

app:
  auth:
    tokenSecret: ${TOKEN_SECRET:04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1}
    tokenExpirationMsec: ${TOKEN_EXPIRATION:864000000}
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
