spring:
  security:
    oauth2.client:
      registration:
        google:
          clientId: ${OAUTH_GOOGLE_CLIENT_ID:id}
          client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET:secret}
          scope:
            - email
            - profile
        kakao:
          client-id: ${OAUTH_KAKAO_CLIENT_ID:id}
          redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
          client-authentication-method: POST
          authorization-grant-type: authorization_code
          scope:
            - profile_nickname
            - profile_image
            - account_email
        github:
          client-id: ${OAUTH_GITHUB_CLIENT_ID:id}
          client-secret: ${OAUTH_GITHUB_CLIENT_SECRET:secret}
          scope:
            - user
      provider:
        kakao:
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me
          user-name-attribute: id
  data:
    mongodb:
      host: ${MONGO_DB_HOST:localhost}
      port: ${MONGO_DB_PORT:27017}
      username: ${MONGO_DB_USERNAME:username}
      password: ${MONGO_DB_PASSWORD:password}
      database: onlineJudgeDB
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:pass}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:test@gmail.com}
    password: ${MAIL_PASSWORD:1234}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

app:
  auth:
    tokenSecret: ${TOKEN_SECRET:04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1}
    accessTokenExp: ${ACCESS_TOKEN_EXPIRATION:3600}
    refreshTokenExp: ${REFRESH_TOKEN_EXPIRATION:1209600}
  oauth2:
    authorizedRedirectUris: ${OAUTH_REDIRECT_URIS:http://localhost:3000/oauth2/redirect}
  verify-url: ${FRONT_DOMAIN:http://localhost}${VERIFY_URL:/verify?code=%s}
  reset-password-url: ${FRONT_DOMAIN:http://localhost}${RESET_PASSWORD_URL:/reset-password?code=%s}

springdoc:
  swagger-ui:
    tagsSorter: alpha
    operationsSorter: method

logging:
  level:
    yoonleeverse.onlinejudge: debug